# Generated by Django 3.2 on 2021-06-06 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('text', models.TextField(max_length=300)),
                ('image', models.TextField(max_length=30)),
                ('genre', models.TextField(max_length=30)),
                ('url', models.TextField(max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_text', models.TextField(max_length=1000)),
                ('do_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('check_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('action_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('plan_date', models.DateField(blank=True, null=True)),
                ('do_start', models.DateField(blank=True, null=True)),
                ('do_end', models.DateField(blank=True, null=True)),
                ('check_date', models.DateField(blank=True, null=True)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-plan_date',),
            },
        ),
    ]
